volumes:
  palserver-installdir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PALSERVER_INSTALLDIR}
secrets:
  admin_password:
    file: ${ADMIN_PASSWORD_FILE}
  server_password:
    file: ${SERVER_PASSWORD_FILE}
services:
  install_or_update:
    image: ghcr.io/tsuereth/steamcmd-install-app:latest
    command: "2394010"
    environment:
      - CHOWN_UID_GID=1000:1000
    volumes:
      - palserver-installdir:/install-dir-volume
    restart: "no"
  game:
    build:
      context: palserver-container/
    depends_on:
      install_or_update:
        condition: service_completed_successfully
    secrets:
      - admin_password
      - server_password
    environment:
      - RUNAS_UID=1000
      - RUNAS_GID=1000
      - PALSERVER_DATA_PATH=/palserver
      - SERVER_NAME="My Palworld Server"
      - SERVER_DESCRIPTION="There are many like it, but this one is mine"
      - ADMIN_PASSWORD_FILE=/run/secrets/admin_password
      - SERVER_PASSWORD_FILE=/run/secrets/server_password
      - PUBLIC_LOBBY=True
    volumes:
      - palserver-installdir:/palserver
    ports:
      - "0.0.0.0:8211:8211/udp"
    expose:
      - "8212"
    deploy:
      resources:
        reservations:
          cpus: '1.0'
          memory: 8G
        limits:
          cpus: '2.0'
          memory: 16G
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --user admin:$$(cat /run/secrets/admin_password) http://localhost:8212/v1/api/info"]
      interval: 15s
      timeout: 1s
      retries: 1
      start_period: 15s
  metrics_exporter:
    image: ghcr.io/tsuereth/palserver-metrics-exporter:latest
    command: --palserver-host=game --palserver-admin-password-file=/run/secrets/admin_password
    depends_on:
      game:
        condition: service_healthy
    secrets:
      - admin_password
    ports:
      - "0.0.0.0:8213:8213"
